#server:
#  port: 9191
#spring:
#  zipkin:
#    base-url: http:'//localhost:9411/
#  h2:
#    console:
#      enabled: true
#  application:
#    name: payment-service
#  cloud:
#    config:
#      enabled: false
#      uri:
#        - http:'//localhost:9196
#logging:
#  file: /home/pratheush/jlab/my_idea_projects/mymicroservice_javatechie/oms.log

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  ratelimiter:
      instances:
        UNSTABLE_DO_PAYMENT:
          limitForPeriod: 2
          limitRefreshPeriod: 10s
