#server:
#  port: 9192
#spring:
  #zipkin:
   # base-url: http:'//localhost:9411/
 # h2:
 #   console:
 #     enabled: true
 # application:
  #  name: order-service
  #loud:
  #  config:
  #    enabled: false
#logging:
  #file: /home/pratheush/jlab/my_idea_projects/mymicroservice_javatechie/oms.log
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      unstable-save-order:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 6
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
  bulkhead:
    instances:
      unstable-save-order:
        maxConcurrentCalls: 8
        maxWaitDuration: 50s


